### ISSUE TITLE
frc-captcha always empty

### ISSUE THREAD

**Issue by jeanassysisu** [Elma/friendly-captcha-bundle#10]
Hello,

I installed the bundle and followed the instructions, however the div with class frc-captcha is always empty:

```
<div class="frc-captcha" data-sitekey="##############" data-solution-field-name="form[captcha]" data-puzzle-endpoint="https://eu-api.friendlycaptcha.eu/api/v1/puzzle" data-start="focus">
    </div>
```

Any idea what could the reason be?

**Comment by elernonelma** [comment]
Hi @jeanassysisu ; the associated twig template expose what you should be able to see https://github.com/Elma/friendly-captcha-bundle/blob/main/src/Resources/views/friendlycaptcha.html.twig
= exactly nothing inside the div itself.

Did you attende to see something else?

**Comment by jeanassysisu** [comment]
@elernonelma thanks for the reply. Isnt it supposed to show the captcha?

Also, if i try to submit the form, i get a validation error "Friendly Captcha is Invalid"

**Comment by elernonelma** [comment]
You're welcome, you simply have to call the related javascript cf https://friendlycaptcha.com/#developers ; this bundle helps you to render the "widget" part, and to make the server to server call at symfony validation.

**Comment by jeanassysisu** [comment]
Thanks for the clarification :)
